export const BIZ={name:'Rangrez Studio',city:'Rajkot, Gujarat',about:'A small handmade-gifts studio selling soy candles, cotton kurtas, spice gift boxes and tote bags. Team of 5.',voice:'Warm, short and friendly. Mention handmade and Rajkot when natural. Never promise anything the policies do not say.',
products:[{n:'Handmade Candles',p:349,s:18,r:4,tag:'soy wax, 8 fragrances, 40-hour burn'},{n:'Cotton Kurta',p:1199,s:42,r:6,tag:'block-printed, sizes S to XXL'},{n:'Spice Gift Box',p:799,s:75,r:5,tag:'6 hand-ground masalas in a wooden box'},{n:'Tote Bag',p:299,s:9,r:3,tag:'canvas, hand-painted designs'}],
faqs:[{q:'What is your return policy?',a:'Returns are accepted within 7 days of delivery if the item is unused. Candles and food items cannot be returned once opened.'},{q:'How long does delivery take and what does shipping cost?',a:'Delivery takes 2 to 4 days within Gujarat and 4 to 6 days across India. Shipping is free above ₹999, otherwise ₹60.'},{q:'Do you offer cash on delivery?',a:'Yes, cash on delivery is available within Gujarat for orders up to ₹3,000. UPI and cards are accepted everywhere.'},{q:'What are your opening hours?',a:'We reply every day from 10 AM to 8 PM. The studio is closed on Sundays.'},{q:'Can I order a custom gift hamper?',a:'Yes. Custom hampers need 3 days notice. Share your budget and the studio will confirm a design.'}],
orders:[{id:'ORD-1042',who:'Meera Shah',item:'Handmade Candles x2',st:'Shipped',eta:'arriving tomorrow'},{id:'ORD-1043',who:'Karan Joshi',item:'Cotton Kurta',st:'Packed',eta:'arriving in 3 days'},{id:'ORD-1044',who:'Pooja Patel',item:'Spice Gift Box',st:'Delivered',eta:'delivered yesterday'}],
sales:[42,48,51,47,55,61,66,64,72,78,85,91],ch:[['Email',6.2],['Instagram',3.1],['Google Ads',2.4],['Facebook',1.8]]};
export const R={
en:{hi:'Hi! How can I help you today?',order:'Your order has shipped and will arrive by tomorrow.',hours:'We are open every day, 9 AM to 9 PM.',esc:'This looks sensitive, so I am passing it to a team member who will reply personally.',d:'I did not quite get that. Could you rephrase?',c:['Where is my order?','What are your hours?','I want a refund']},
hi:{hi:'नमस्ते! मैं आपकी कैसे मदद कर सकता हूँ?',order:'आपका ऑर्डर भेज दिया गया है और कल तक पहुँच जाएगा।',hours:'हम रोज़ सुबह 9 से रात 9 बजे तक उपलब्ध हैं।',esc:'यह मामला संवेदनशील है। मैं इसे हमारी टीम के सदस्य को भेज रहा हूँ।',d:'मैं समझ नहीं पाया। क्या आप दूसरे शब्दों में बता सकते हैं?',c:['मेरा ऑर्डर कहाँ है?','आपका समय क्या है?','मुझे रिफंड चाहिए']},
gu:{hi:'નમસ્તે! હું તમારી કેવી રીતે મદદ કરી શકું?',order:'તમારો ઓર્ડર મોકલી દેવાયો છે અને કાલ સુધીમાં પહોંચી જશે.',hours:'અમે રોજ સવારે 9 થી રાત્રે 9 સુધી ઉપલબ્ધ છીએ.',esc:'આ બાબત સંવેદનશીલ છે. હું તેને અમારી ટીમના સભ્યને મોકલી રહ્યો છું.',d:'મને સમજાયું નહીં. શું તમે બીજી રીતે કહી શકો?',c:['મારો ઓર્ડર ક્યાં છે?','તમારો સમય શું છે?','મારે રિફંડ જોઈએ છે']}};
export const LN={en:'English',hi:'Hindi',gu:'Gujarati'},ESC=/refund|complain|legal|cancel|angry|money back|રિફંડ|રિફન્ડ|ફરિયાદ|रिफंड|शिकायत/i;
export const SRC={ai:'AI answer from business data',kb:'Matched from business data',esc:'Sent to human queue',none:'Not found in business data'};
export const STOP=new Set('the you your what are how can for and with have does this that from who when where which will our get any please about order orders take long much there'.split(' '));
export const tok=t=>t.toLowerCase().split(/[^a-z0-9]+/).filter(w=>w.length>2&&!STOP.has(w));
export const cap=t=>t[0].toUpperCase()+t.slice(1),TY={caption:'Instagram caption',ad:'short ad',blog:'blog post intro (2 to 3 sentences)'},TN={friendly:'friendly',bold:'bold',pro:'professional'};
export const T={caption:{friendly:[o=>`${o.n}, handmade in Rajkot. ${cap(o.tag)}. From ₹${o.p}. Link in bio.`,o=>`Say hello to ${o.n}: ${o.tag}. Made with care by our small team.`],bold:[o=>`${o.n}. ${cap(o.tag)}. ₹${o.p}. Yours today.`,o=>`Handmade beats mass-made. ${o.n} is live now.`],pro:[o=>`Introducing ${o.n}: ${o.tag}. Priced at ₹${o.p}.`,o=>`${o.n} by ${BIZ.name}, crafted in small batches in Rajkot.`]},
ad:{friendly:[o=>`Love handmade? Meet ${o.n} at ₹${o.p}. Free shipping above ₹999.`,o=>`${cap(o.tag)}. ${o.n}, only ₹${o.p}.`],bold:[o=>`${o.n} for ₹${o.p}. Order today.`,o=>`Only ${o.s} left: ${o.n}.`],pro:[o=>`${o.n}: ${o.tag}. Delivered across India.`,o=>`Quality you can feel. ${o.n} from ${BIZ.name}.`]},
blog:{friendly:[o=>`Every ${o.n.toLowerCase()} we make starts by hand in Rajkot. Here is what goes into it: ${o.tag}.`],bold:[o=>`Why does handmade cost more? Look at ${o.n}: ${o.tag}.`],pro:[o=>`${BIZ.name} produces ${o.n.toLowerCase()} in small batches. This article explains the process: ${o.tag}.`]}};
export const DAYS=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
export const MN=['Oct','Nov','Dec','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep'];
export const SCHED0=[{d:0,t:'Weekend launch teaser',s:'Scheduled'},{d:2,t:'Customer story: how 5 people do the work of 15',s:'Scheduled'},{d:4,t:'Flash sale reminder',s:'Scheduled'}];
export const CHIPS={en:['Where is ORD-1042?','How much is the Cotton Kurta?','Do you do COD?','What is your return policy?','I want a refund'],hi:R.hi.c,gu:R.gu.c};
